[pytest]
addopts = --strict-markers --strict-config
testpaths = tests
markers =
    virtual: Tests with virtual drive
    ethernet: Ethernet tests
    ethercat: EtherCAT tests
    eoe: EtherCAT service tests
    canopen: CANopen tests
    multislave: EtherCAT tests that require multiple slaves
    no_pcap: Test for environments without libpcap/WinPcap/Npcap installed
    pcap: Test for environments that only require libpcap/WinPcap/Npcap installed but no real ethercat network
    fsoe: Safety over EtherCAT
log_cli = False
log_cli_level = INFO
env=
    D:TESTS_OUTPUT_DIR=tests/outputs
    D:RESOURCES_DIR=resources
    D:WIRESHARK_DIR=wireshark
    D:WIRESHARK_INSTALLATION_PATH=C:\\Program Files\\Wireshark
    D:START_WIRESHARK_TIMEOUT_S=10.0