line-length = 100
target-version = "py39"

[lint]
pydocstyle.convention = "google"
select = [
    "ALL",
]
ignore = [
    "ANN", # flake8-annotations
    "C90", # mccabe complexity
    "D100", # Missing docstring in public module
    "D104", # Missing docstring in public package
    "D107", # Missing docstring in __init__
    "FA100", # Missing `from __future__ import annotations`
    "FIX002", # TODO comment
    "G004", # Logging statement uses f-string
    "S314", # Insecure XML parser,
    "SLF001", # Private member accessed
    "TD002", # Missing author in TODO
    "TD003", # Missing issue link in TODO
    "TRY003", # Avoid specifying long messages outside the exception class
    "COM812", # Trailing comma. Already enforced by the formatter.
    "ISC001", # Implicitly concatenated strings. Already enforced by the formatter.
]
[lint.per-file-ignores]
"ingenialink/network.py" = [
    "D102", # Missing docstring in public method
]
"tests/*" = [
    "D", # Docstring rules
    "ERA001", # Commented-out code
    "S101", # Use of assert keyword
    "PLR2004", # Magic value comparison
    "PT004", # Missing fixture name underscore
]
"virtual_drive/*" = [
    "D", # Docstring rules
    "ERA001", # Commented-out code
]