line-length = 100
target-version = "py39"

[lint]
select = [
    "F", # Pyflakes
    "E", # pycodestyle
    "W", # pycodestyle
    "I", # isort
    "N", # pep8-naming
]
pydocstyle.convention = "google"