class UdpStack:
    def __init__(self, mac: str, ip: str, prefix_len: int) -> None: ...
    def push_frame(self, frame: bytes) -> None: ...
    def pop_frame(self) -> bytes | None: ...
    def poll(self) -> bool: ...
    def bind(self, port: int) -> None: ...
    def send(self, src_port: int, dst_ip: str, dst_port: int, payload: bytes) -> None: ...
    def recv(self, port: int) -> tuple[bytes, str, int] | None: ...
